AWS_ACCESS_KEY_ID = "u7lALw0XwctulsPmfkLwt8SbtolQzuBGt8nUDTQktX6JlpsPJiBbJsimITxOy43N" 
AWS_SECRET_ACCESS_KEY = "kfpYjfQ1PRqFYm7V0Pu1VgYgFOqMv70KyVP9FvzoIuz8LM3O39c80bVTU7F5xoZC"
AWS_DEFAULT_REGION = 'us-east-1'

